// <auto-generated />
using System;
using System.Collections.Generic;
using HouseOs.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseOs.Api.Infrastructure.Migrations
{
    [DbContext(typeof(HouseOsDbContext))]
    [Migration("20260824222442_AjouterDocuments")]
    partial class AjouterDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseOs.Api.Domaine.CompteARebours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateCible")
                        .HasColumnType("date");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ComptesARebours");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CheminDisque")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateDocument")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Echeance")
                        .HasColumnType("date");

                    b.Property<Guid?>("EquipementId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("Taille")
                        .HasColumnType("bigint");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TypeMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Categorie");

                    b.HasIndex("Echeance");

                    b.HasIndex("EquipementId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.EntreeJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompleteeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Cout")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TacheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TacheId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Journal");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Equipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateAchat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FinGarantie")
                        .HasColumnType("date");

                    b.Property<string>("Marque")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modele")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Dictionary<string, string>>("Specs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.EvenementExterne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("FluxExterneId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("Heure")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("FluxExterneId");

                    b.ToTable("EvenementsExternes");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.FluxExterne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("DernierRafraichissementLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DerniereErreur")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("FluxExternes");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Humeur.PhraseDuJour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("GenereLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Moment")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SousTitre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Moment")
                        .IsUnique();

                    b.ToTable("PhrasesDuJour");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Meteo.PrevisionHoraire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CouvertureNuageusePct")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Heure")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HumiditePct")
                        .HasColumnType("integer");

                    b.Property<double?>("HumiditeSol")
                        .HasColumnType("double precision");

                    b.Property<double>("IndiceUv")
                        .HasColumnType("double precision");

                    b.Property<double>("PrecipitationMm")
                        .HasColumnType("double precision");

                    b.Property<int>("ProbabilitePrecipitationPct")
                        .HasColumnType("integer");

                    b.Property<double>("RafalesKmh")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double>("VentKmh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Heure")
                        .IsUnique();

                    b.ToTable("PrevisionsHoraires");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Meteo.PrevisionQuotidienne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeMeteo")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Coucher")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("IndiceUvMax")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly>("Lever")
                        .HasColumnType("time without time zone");

                    b.Property<double>("PrecipitationMm")
                        .HasColumnType("double precision");

                    b.Property<int>("ProbabilitePrecipitationMaxPct")
                        .HasColumnType("integer");

                    b.Property<double>("RafalesMaxKmh")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxC")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinC")
                        .HasColumnType("double precision");

                    b.Property<double>("VentMaxKmh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PrevisionsQuotidiennes");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Meteo.ReleveMeteo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RecupereLe")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RelevesMeteo");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Occurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneAId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompleteeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompleteeParId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Echeance")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("PasseeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TacheId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssigneAId");

                    b.HasIndex("CompleteeParId");

                    b.HasIndex("TacheId");

                    b.HasIndex("Statut", "Echeance");

                    b.ToTable("Occurrences");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Tache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneAId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreeParId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EquipementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Strategie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssigneAId");

                    b.HasIndex("EquipementId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("JetonIcal")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomAffichage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Document", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.Equipement", null)
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HouseOs.Api.Domaine.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.EntreeJournal", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Equipement", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.EvenementExterne", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.FluxExterne", null)
                        .WithMany("Evenements")
                        .HasForeignKey("FluxExterneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Occurrence", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.Utilisateur", "AssigneA")
                        .WithMany()
                        .HasForeignKey("AssigneAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HouseOs.Api.Domaine.Utilisateur", "CompleteePar")
                        .WithMany()
                        .HasForeignKey("CompleteeParId");

                    b.HasOne("HouseOs.Api.Domaine.Tache", "Tache")
                        .WithMany("Occurrences")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssigneA");

                    b.Navigation("CompleteePar");

                    b.Navigation("Tache");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Tache", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.Utilisateur", "AssigneA")
                        .WithMany()
                        .HasForeignKey("AssigneAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HouseOs.Api.Domaine.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HouseOs.Api.Domaine.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("HouseOs.Api.Domaine.SpecRecurrence", "Recurrence", b1 =>
                        {
                            b1.Property<Guid>("TacheId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("FenetreDebutJour")
                                .HasColumnType("integer")
                                .HasColumnName("FenetreDebutJour");

                            b1.Property<int?>("FenetreDebutMois")
                                .HasColumnType("integer")
                                .HasColumnName("FenetreDebutMois");

                            b1.Property<int?>("FenetreFinJour")
                                .HasColumnType("integer")
                                .HasColumnName("FenetreFinJour");

                            b1.Property<int?>("FenetreFinMois")
                                .HasColumnType("integer")
                                .HasColumnName("FenetreFinMois");

                            b1.Property<string>("FixeType")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("FixeType");

                            b1.Property<int?>("IntervalleJours")
                                .HasColumnType("integer")
                                .HasColumnName("IntervalleJours");

                            b1.Property<int?>("JourAnnuel")
                                .HasColumnType("integer")
                                .HasColumnName("JourAnnuel");

                            b1.Property<int?>("JourDuMois")
                                .HasColumnType("integer")
                                .HasColumnName("JourDuMois");

                            b1.Property<int?>("JoursSemaineMasque")
                                .HasColumnType("integer")
                                .HasColumnName("JoursSemaineMasque");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Mode");

                            b1.Property<int?>("MoisAnnuel")
                                .HasColumnType("integer")
                                .HasColumnName("MoisAnnuel");

                            b1.Property<bool>("Rollover")
                                .HasColumnType("boolean")
                                .HasColumnName("Rollover");

                            b1.HasKey("TacheId");

                            b1.ToTable("Taches");

                            b1.WithOwner()
                                .HasForeignKey("TacheId");
                        });

                    b.Navigation("AssigneA");

                    b.Navigation("Equipement");

                    b.Navigation("Recurrence")
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.FluxExterne", b =>
                {
                    b.Navigation("Evenements");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Tache", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
