// <auto-generated />
using System;
using HouseOs.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseOs.Api.Infrastructure.Migrations
{
    [DbContext(typeof(HouseOsDbContext))]
    partial class HouseOsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseOs.Api.Domaine.EntreeJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompleteeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Cout")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TacheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TacheId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Journal");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Occurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompleteeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompleteeParId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Echeance")
                        .HasColumnType("date");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TacheId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompleteeParId");

                    b.HasIndex("TacheId");

                    b.HasIndex("Statut", "Echeance");

                    b.ToTable("Occurrences");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Tache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneAId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreeParId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Rollover")
                        .HasColumnType("boolean");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneAId");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomAffichage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.EntreeJournal", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Occurrence", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.Utilisateur", "CompleteePar")
                        .WithMany()
                        .HasForeignKey("CompleteeParId");

                    b.HasOne("HouseOs.Api.Domaine.Tache", "Tache")
                        .WithMany("Occurrences")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompleteePar");

                    b.Navigation("Tache");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Tache", b =>
                {
                    b.HasOne("HouseOs.Api.Domaine.Utilisateur", "AssigneA")
                        .WithMany()
                        .HasForeignKey("AssigneAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssigneA");
                });

            modelBuilder.Entity("HouseOs.Api.Domaine.Tache", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
